server:
  port: ${PORT:8080}

spring:
  application:
    name: blog-system
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME:}
    password: ${DATABASE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
  level:
    com.blog: info
